### ISSUE TITLE
testest is now Ropsten

### ISSUE THREAD

**Issue by wighawag** [MetaMask/hello#37] opened 2016-11-20 22:35 UTC
Hi, you are probably already on it but in case not, adding Ropsten (making the default too) would be good.
See : https://blog.ethereum.org/2016/11/20/from-morden-to-ropsten/

**Comment by flyswatter** [comment] 2016-11-20 23:07
Good to hear we'll have a nice way out of these Morden issues. We'll be adding Ropsten support soon!

**Comment by flyswatter** [comment] 2016-11-21 17:48
Closed as duplicate of MetaMask/metamask-plugin#831

**Closed** 2016-11-21 17:47 UTC
Labels: in progress
