### ISSUE TITLE
Import Old Wallets

### ISSUE THREAD

**Issue by lowend** [MetaMask/hello#36] opened 2016-11-11 01:46 UTC
Hi there,

Is there a way to import wallets from mist?

Additionally, with that functionality using the web version of the mist browser to interact with multi-sig wallet contracts?

Thanks!

**Comment by Zanibas** [comment] 2016-11-11 02:13
We are currently in the process of implementing Multi-Wallet support, which includes importing wallets from say, Mist! You can follow our progress on the MultiVault branch on the plugin.

As for interactig with multi-sig wallet contracts, we'll take that into consideration as we continue to develop the feature.

**Comment by flyswatter** [comment] 2016-11-22 02:34
Closing as duplicate of #715

**Closed by flyswatter** 2016-11-22 02:34 UTC
